[source]
host = "172.17.0.1"
port = "3306"
user = "root"
password = ""
database = "a" # can not be empty

[destination]
host = "172.17.0.1" # no import if host is empty
port = "3307"
user = "root" # no import if user is empty
password = ""
database = "" # if it's empty, we will use the same db name as source

[option]
no-data = true # set this to false if you want to dump data
ignore-table = [
	"migrations",
	"schema_migrations"
]
